### ISSUE TITLE
IDBIndex is not defined

### ISSUE THREAD

**Issue by ajaykumarsaini** [jakearchibald/indexeddb-promised#4]
I am working on single page web app and trying to make it offline using serviceworker and IndexedDb, But I am not able to use this library for IndexedDb becasue during the gulp serve it is throwing this: 'ReferenceError: IDBIndex is not defined
    at /home/user/Desktop/cincinati/my_app/node_modules/idb/lib/idb.js:87:40' tell me what to do
'

**Comment by jakearchibald** [comment]
This library is designed to run in the browser, not in node. Or am I misunderstanding the issue?

**Comment by jakearchibald** [comment]
Closing due to lack of feedback - feel free to reopen
