### ISSUE TITLE
Import idb from 'idb' not Working

### ISSUE THREAD

**Issue by barcealona** [jakearchibald/indexeddb-promised#5]
Thid Command not Working.
Can you step by step explain how do you make this command working

**Comment by jakearchibald** [comment]
This library is designed to run in the browser. Given that no browser supports imports yet, I guess you've missed out some details?

**Comment by jakearchibald** [comment]
Closing due to lack of feedback - feel free to reopen

**Comment by neerajnarayanan** [comment]
do idb can be used along with s-w toolbox in ServiceWorker?i want to store my form details into idb offline and get it back when fetched.

**Comment by KeithHenry** [comment]
@neerajnarayanan that question isn't related to this thread, but yes, you should be able to use idb, just not from the page. You'll have to `require` it in the service worker setup.

**Comment by neerajnarayanan** [comment]
can anybody answer this question https://stackoverflow.com/questions/43126572/how-can-i-add-contents-to-indexeddb-using-serviceworker
