### ISSUE TITLE
Ability to keep transaction open while writes are happening every X seconds?

### ISSUE THREAD

**Issue by silverbucket** [jakearchibald/indexeddb-promised#6]
I've got a project which writes to IndexedDB in spurts of possibly ~100-1000 writes within 30-60seconds. Traditionally, if a transaction closes after every write, the performance is awful. So I was wondering if this library could be used to keep a transaction open for X amount of seconds after the last write? This way, after a burst of writes, the transaction would close within a few seconds. With home-brew testing the performance increases considerably, however there are other intricacies of the IndexedDB API that I was having some trouble with and thought it might be better to find an existing (lightweight) library which takes this use-case into account.

**Comment by jakearchibald** [comment]
Unfortunately there's no way to extend the lifetime of a transaction in IndexedDB, and it isn't something this library can add in.

@inexorabletash is proposing `tx.waitUntil` is added to the spec. This means you can do something like:

```js
function wait(ms) {
  return new Promise(r => setTimeout(r, ms));
}

transaction.waitUntil(
  wait(5000).then(…)
);
```

…which would keep the transaction open.

You could add a layer on top that buffers writes, and only commits them to IDB every 30 seconds, but those changes won't show up in your reads, and that data might be lost if the tab closes before commiting.

**Comment by inexorabletash** [comment]
As specified, an open read/write transaction will block a read-only transaction with overlapping scope, so you probably don't want to hold the transaction open.
