### ISSUE TITLE
Unable to idb.open()

### ISSUE THREAD

**Issue by vinz** [jakearchibald/indexeddb-promised#7]
Hi Jake,

Thanks for such amazing library.
It has greatly simplified and enhanced developer experience w.r.t. working with Indexed DB.

It has been awesome so far, until recently we tried running our app on iOS safari and iOS chrome.
Unfortunately site doesn't seem to open at all!!

We examined and found that issue is because of IndexedDB Promised API.

We tried connecting our iPhone and tried remote safari debugger.
It throws following error message.

<img width="488" alt="screen shot 2016-09-04 at 9 00 55 pm" src="https://cloud.githubusercontent.com/assets/1381269/18231981/6237de76-72e3-11e6-9003-026c7e72a786.png">

Later, we also found that it doesn't even open on Desktop Safari!!! Same error!!

Can you please look into the issue and see if you can fix it.

Thanks, Vinay

**Comment by jakearchibald** [comment]
I can't recreate this on desktop Safari. Which version of desktop Safari are you using?

What do you get in the console when you run http://output.jsbin.com/docoqa/quiet?

**Comment by vinz** [comment]
Thanks for such quick reply :)

We are running Desktop Safari Version 9.1.3 (11601.7.8)

We just found out that the error occurs only on Incognito mode. This is strange!!
It works without any issues in normal mode both on desktop Safari and mobile (iPhone and iPad on both Safari mobile and Chrome iOS).

Even the link which you gave does not seem to work in Incognito mode.

Can you please check if this can be fixed.

Thanks, Vinay

**Comment by jakearchibald** [comment]
Unfortunately it can't be fixed. IDB doesn't exist in Safari in incognito mode, or in add-to-homescreen mode on iOS. There's nothing I can't do about it, it's just not there.

**Comment by vinz** [comment]
Oh okay. Cool no prob.
Thanks for the info :)
Happy Coding. Cya.
